"""Pure LTR readiness field catalog for Phase 7."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class ReadinessSeverity(StrEnum):
    """Readiness handling policy for an LTR field."""

    BLOCKER = "BLOCKER"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    PLACEHOLDER_ALLOWED = "PLACEHOLDER_ALLOWED"


@dataclass(frozen=True, slots=True)
class LtrFieldDefinition:
    """Definition of one LTR readiness field."""

    key: str
    display_label: str
    source_paths: tuple[str, ...]
    fallback_policy: str
    severity: ReadinessSeverity
    placeholder_policy: str | None
    operator_action: str


LTR_FIELD_CATALOG: tuple[LtrFieldDefinition, ...] = (
    LtrFieldDefinition(
        key="dl",
        display_label="DL",
        source_paths=("ltr.preview.proposed_ltr_number", "ltr_record.ltr_number"),
        fallback_policy="Generated by LTR preview before commit.",
        severity=ReadinessSeverity.BLOCKER,
        placeholder_policy=None,
        operator_action="Preview and confirm the proposed DL number before registration.",
    ),
    LtrFieldDefinition(
        key="project_type",
        display_label="Project Type",
        source_paths=("application_form.project_type",),
        fallback_policy="Manual confirmation from the selected application form.",
        severity=ReadinessSeverity.BLOCKER,
        placeholder_policy=None,
        operator_action="Confirm project type before LTR registration.",
    ),
    LtrFieldDefinition(
        key="description_pn",
        display_label="Description P/N",
        source_paths=("sample_info.part_number", "sample_info.product_name"),
        fallback_policy="Manual confirmation from confirmed sample rows.",
        severity=ReadinessSeverity.BLOCKER,
        placeholder_policy=None,
        operator_action="Confirm sample part number and description.",
    ),
    LtrFieldDefinition(
        key="test_item",
        display_label="Test Item",
        source_paths=("application_form.requested_testing",),
        fallback_policy="Manual confirmation from requested testing text.",
        severity=ReadinessSeverity.BLOCKER,
        placeholder_policy=None,
        operator_action="Confirm the requested test item.",
    ),
    LtrFieldDefinition(
        key="applicable_specifications",
        display_label="Applicable Specifications",
        source_paths=(
            "file_assets.specification",
            "intake_assets.supporting_specification",
            "application_form.requested_testing",
        ),
        fallback_policy="Select supporting specification evidence or confirm manually.",
        severity=ReadinessSeverity.BLOCKER,
        placeholder_policy=None,
        operator_action="Attach or confirm applicable specifications.",
    ),
    LtrFieldDefinition(
        key="test_type",
        display_label="Test Type",
        source_paths=("application_form.test_type",),
        fallback_policy="Manual confirmation from the application form.",
        severity=ReadinessSeverity.BLOCKER,
        placeholder_policy=None,
        operator_action="Confirm test type.",
    ),
    LtrFieldDefinition(
        key="requested_by",
        display_label="Requested by",
        source_paths=("application_form.requester", "project.requestor", "intake_package.sender_name"),
        fallback_policy="Use sender only after operator confirmation.",
        severity=ReadinessSeverity.BLOCKER,
        placeholder_policy=None,
        operator_action="Confirm the requestor name.",
    ),
    LtrFieldDefinition(
        key="location",
        display_label="Location",
        source_paths=("application_form.manufacturing_site", "application_form.lab"),
        fallback_policy="Manual confirmation if manufacturing site or lab location is missing.",
        severity=ReadinessSeverity.REVIEW_REQUIRED,
        placeholder_policy=None,
        operator_action="Confirm the location to write into the LTR workbook.",
    ),
    LtrFieldDefinition(
        key="project_leader",
        display_label="Project Leader",
        source_paths=("application_form.assigned_personnel",),
        fallback_policy="Manual confirmation by the lab operator.",
        severity=ReadinessSeverity.REVIEW_REQUIRED,
        placeholder_policy=None,
        operator_action="Confirm assigned personnel or project leader.",
    ),
    LtrFieldDefinition(
        key="test_result",
        display_label="Test Result",
        source_paths=(),
        fallback_policy="Result is not available at registration time.",
        severity=ReadinessSeverity.PLACEHOLDER_ALLOWED,
        placeholder_policy='Use "Pending" until test results are recorded.',
        operator_action="No registration block; keep the explicit placeholder.",
    ),
    LtrFieldDefinition(
        key="failed_item",
        display_label="Failed item",
        source_paths=(),
        fallback_policy="Failure details are not available at registration time.",
        severity=ReadinessSeverity.PLACEHOLDER_ALLOWED,
        placeholder_policy='Use "N/A" until failures are known.',
        operator_action="No registration block; keep the explicit placeholder.",
    ),
    LtrFieldDefinition(
        key="sample_deposition",
        display_label="Sample deposition",
        source_paths=("application_form.post_testing_disposition",),
        fallback_policy="Manual confirmation from post-testing disposition.",
        severity=ReadinessSeverity.REVIEW_REQUIRED,
        placeholder_policy=None,
        operator_action="Confirm sample disposition policy.",
    ),
    LtrFieldDefinition(
        key="sub_contract",
        display_label="Sub-contract",
        source_paths=("application_form.subcontract_allowed", "application_form.subcontract"),
        fallback_policy="Manual confirmation if parsed subcontract value is ambiguous.",
        severity=ReadinessSeverity.BLOCKER,
        placeholder_policy=None,
        operator_action="Confirm whether subcontracting is allowed.",
    ),
    LtrFieldDefinition(
        key="test_fee",
        display_label="Test Fee",
        source_paths=(),
        fallback_policy="Manual fee confirmation or explicit no-fee policy.",
        severity=ReadinessSeverity.REVIEW_REQUIRED,
        placeholder_policy=None,
        operator_action="Confirm test fee handling before final workbook write.",
    ),
    LtrFieldDefinition(
        key="remarks_po",
        display_label="Remarks (PO)",
        source_paths=("application_form.additional_information",),
        fallback_policy="Optional manual note; confirm blank-by-policy if empty.",
        severity=ReadinessSeverity.REVIEW_REQUIRED,
        placeholder_policy=None,
        operator_action="Review remarks or PO note policy.",
    ),
    LtrFieldDefinition(
        key="phone",
        display_label="Phone",
        source_paths=("application_form.phone",),
        fallback_policy="Manual confirmation from request package if missing.",
        severity=ReadinessSeverity.BLOCKER,
        placeholder_policy=None,
        operator_action="Confirm requestor phone number.",
    ),
    LtrFieldDefinition(
        key="requestor_email",
        display_label="E-mail of Requestor",
        source_paths=("application_form.email", "intake_package.sender_email"),
        fallback_policy="Use sender email only after operator confirmation.",
        severity=ReadinessSeverity.BLOCKER,
        placeholder_policy=None,
        operator_action="Confirm requestor email address.",
    ),
    LtrFieldDefinition(
        key="product_description",
        display_label="Product Description",
        source_paths=("project.product_name", "sample_info.product_name"),
        fallback_policy="Manual confirmation from project or sample description.",
        severity=ReadinessSeverity.BLOCKER,
        placeholder_policy=None,
        operator_action="Confirm product description.",
    ),
    LtrFieldDefinition(
        key="lab_performing_tests",
        display_label="Lab Performing the Tests",
        source_paths=("application_form.lab",),
        fallback_policy="Use configured/default lab only after manual confirmation.",
        severity=ReadinessSeverity.BLOCKER,
        placeholder_policy=None,
        operator_action="Confirm the lab performing the tests.",
    ),
)


def get_ltr_field_catalog() -> tuple[LtrFieldDefinition, ...]:
    """Return the authoritative LTR readiness field catalog."""
    return LTR_FIELD_CATALOG


def get_ltr_field_definition(key: str) -> LtrFieldDefinition:
    """Return one field definition by canonical key."""
    for definition in LTR_FIELD_CATALOG:
        if definition.key == key:
            return definition
    raise KeyError(f"Unknown LTR readiness field key: {key}")
